name: CI Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  test_and_lint:
    runs-on: ubuntu-latest
    container:
      image: python:3.7

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start Uvicorn Server
        run: |
          nohup uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload &

      - name: Wait for server to start
        run: |
          sleep 5

      - name: Run Unit Tests
        run: pytest tests

      - name: Run black
        run: black --diff --check app/

      - name: Run isort
        run: isort --check-only --diff --profile black app/

      - name: Run mypy
        run: mypy app/

      - name: Stop Uvicorn Server
        run: |
          pkill -f "uvicorn app.main:app"

      - name: Run flake8
        run: flake8 app/
