name: CI Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  test_and_lint:
    runs-on: ubuntu-latest
    container:
      image: python:3.7

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Unit Tests
        run: pytest tests

      - name: Run black
        run: black --diff --check main/

      - name: Run isort
        run: isort --check-only --diff --profile black main/

      - name: Run mypy
        run: mypy main/

      # - name: Run flake8
      #   run: flake8 main/
